lib/curly/presenter.rb
spec/presenter_spec.rb

This allows ruby to correctly respond in both `#method` and `#respond_to?` calls.  See [this](http://robots.thoughtbot.com/always-define-respond-to-missing-when-overriding).  I encountered this when I was playing around with the `*_path` methods that are defined by Rails; they're defined on the context, but not on the presenter, so attempting to do i.e. `method(:some_path)` would result in a `NameError`.

Add #respond_to_missing? to Curly::Presenter

---

lib/curly/compiler.rb
spec/compiler/context_blocks_spec.rb
spec/dummy/app/views/dashboards/new.html.curly
spec/integration/context_blocks_spec.rb

Weird errors started cropping up when context blocks were being nested. They were caused by Ruby shadowing the buffer variable, making some stuff disappear:
```ruby
buffer = ActiveSupport::SafeBuffer.new
buffer << "one"
old_buffer, buffer = buffer, ActiveSupport::SafeBuffer.new
old_buffer << begin
buffer << "two"
old_buffer, buffer = buffer, ActiveSupport::SafeBuffer.new # This shadows old_buffer
old_buffer << begin
buffer << "three"
end
buffer = old_buffer
end
#close the outer context
buffer = old_buffer # notice that this is not the old_buffer saved by the outer context
buffer.to_s #=> "twothree"
```
In order to make things more reliable, a stack of buffers is employed. This allows us to restore the previous buffer by simply popping it off the stack.

Maintain a stack of output buffers

---

lib/curly/compiler.rb
spec/compiler/collections_spec.rb
spec/spec_helper.rb

Right now, when assigning options to contexts and collections, Curly writes on a common space. With this, the options passed to contexts and collections work as a stack, avoiding undesired rewrites.

Shadowed options bug solved

---

spec/compiler/collections_spec.rb
spec/compiler/context_blocks_spec.rb
spec/compiler_spec.rb
spec/spec_helper.rb

Allow defining the presenters inline in the examples. This allows the presenters to concern themselves only with the needs of a single example.

Clean up the compiler specs

---

lib/curly/compiler.rb
spec/compiler/collections_spec.rb
spec/compiler/context_blocks_spec.rb
spec/dummy/app/presenters/layouts/application_presenter.rb
spec/dummy/app/views/layouts/application.html.curly
spec/integration/application_layout_spec.rb
spec/integration/collection_blocks_spec.rb
spec/integration/context_blocks_spec.rb
spec/integration/partials_spec.rb
spec/spec_helper.rb

If a context or collection constant presenter is named with a name that conflicts with any constant within the `ActionView` scope, the constant from ActionView would prevail; this is a problem, because then you end up with things like `ActionView::Layouts::SomePresenter`, which doesn't exist, being referenced from within the compiled template.
For example:
```Ruby
class Layouts::ApplicationPresenter
def header(&block)
block.call
end
class HeaderPresenter
end
end
```
This would error.  On a side note, I modified `CompilationSupport#render` to allow specification of a presenter, and other things.  A side effect of this is that you must pass locals in as a keyword pair; i.e. `locals: { foo: :bar }`.

Fix Constant Search

---

lib/curly/presenter.rb
spec/presenter_spec.rb

This allows delegation of some methods, i.e. root_path, to the context.  It essentially defines a method on the presenter to allow passing the method directly to the context.  This not only allows the method call to bypass the #method_missing method, it also removes boilerplate code for some methods.
An example, in rails:
```Ruby
class Article::ShowPresenter < Curly::Presenter
presents :article
context_method :root_path
end
```
```HTML
<span class="home-path">{{root_path}}</span>
```

Add .exposes_helper to Presenter

---

lib/curly/component_scanner.rb
lib/curly/parser.rb
lib/curly/scanner.rb
spec/compiler/context_blocks_spec.rb
spec/component_scanner_spec.rb
spec/scanner_spec.rb

**EXPERIMENTAL**
Rather than `{{@author}}{{name}}{{/author}}` it's now possible to write `{{author:name}}`. I'm not sure this is something we want, even if it makes accessing stuff in context blocks easier.
- Multiple levels are allowed, e.g. `{{post:author:name}}`.
- Works for all component types, including blocks, e.g. `{{#post:author:admin?}} ... {{/post:author:admin?}}`.
- ~~Works by modifying the parse tree, so this is valid: `{{#post:author:admin?}} ... {{/author:admin?}}{{/post}}`. I'm not sure that's a good idea, though. Alternatively, the parse tree would hold the namespace and the compiler would unfold it into the tree structure.~~

Add a shorthand syntax for components inside contexts

---

lib/curly/presenter.rb

There's no need for this call to go through `#method_missing`.
Also I an currently profiling all calls to `#method_missing`, and I would like *not* to profile the `#render` calls.

Delegate :render to :@_context

---

lib/curly/compiler.rb
lib/curly/presenter.rb
lib/curly/presenter_name_error.rb
spec/presenter_spec.rb

Instead of relying on two separate bits of logic for presenter
retrieval; One by path and one by class name, leverage the same logic.
In doing this, I am also able to leverage nested lookups as per the
documentation.
Closes #144

Consolidating entry point for presenter retrieval

---

README.md
lib/curly/rspec.rb
spec/dummy/spec/presenters/dashboards/show_presenter_spec.rb

Adds a simple spec type for presenters:
```ruby
require 'curly/rspec'
describe Posts::ShowPresenter, type: :presenter do
describe "#body" do
it "renders the post's body as Markdown" do
assign(:post, double(:post, body: "**hello!**"))
expect(presenter.body).to eq "<strong>hello!</strong>"
end
end
end
```

Add first-class support for testing presenters with RSpec

---

lib/curly/component_compiler.rb
spec/component_compiler_spec.rb

Currently, curly does not support this:
```ruby
def component(**options)
end
```
However, this patch should allow curly to accept and handle these options.  Proper tests are added.

Add Support for :keyrest arguments

---

lib/curly/presenter.rb

There are a few subclasses of `NameError` in which `rescue NameError`
also qualifies; namely, `NoMethodError` also qualifies as a `NameError`,
and as such, would trigger the rescue block incorrectly.  Since any
class can subclass `NameError`, the only real option is to raise if
the error isn't an instance of `NameError`.
I ran into this issue while creating a presenter - I had incorrectly typed a
class method, and as such, it raised a `NoMethodError`, and was handled
oddly by Curly.  This should prevent that issue from happening, but I'm not
sure how to test it.

Add extra check in the presenter class resolution

---

lib/curly/presenter.rb
spec/presenter_spec.rb

This PR is in response to some errors I was getting when running HC locally in Docker (mentioned [here](https://zendesk.slack.com/archives/help-center-dev/p1467925456000063) and [here](https://zendesk.slack.com/archives/help-center-dev/p1468269100000048)). They related to multiple different `Admin` presenters and all had this general form:
```
Curly::PresenterNotFound at /hc/admin/categories/new
error compiling 'admin/translations/_select_source': could not find Admin::Translations::SelectSourcePresenter
```
After a good amount of digging, I discovered that v2.5.0 of this gem worked fine, and that cherry-picking #145 caused the issue to return. I eventually narrowed it down to `const_get` seeing these paths as uninitialized constants. `constantize`, however, seems to resolve the issue. …

Use constantize rather than get_const

---

lib/curly/dependency_tracker.rb

Rails (since 5.0.0) will eventually call `uniq` on it:
https://github.com/rails/rails/blob/v5.0.0/actionview/lib/action_view/digestor.rb#L54-L55

DependencyTracker.call must return Array

---

lib/generators/curly/scaffold/templates/form_presenter.rb.erb
spec/generators/scaffold_curly_generator_spec.rb
spec/generators/scaffold_presenter_generator_spec.rb
spec/presenter_spec.rb

The scaffold generator code had the table `post` hard-coded into it.  I fixed the static issue, and changed the tests from looking at `post` to looking at `article`, so any additional errors should appear.  
Also fixed a warning from Spec.

Fix scaffold generator having static string.

---

CHANGELOG.md
Gemfile
curly-templates.gemspec

Let's allow people to bundle Curly when using Rails 5.2.0.

Rails 5.2.0 support

---

CHANGELOG.md
curly-templates.gemspec
gemfiles/rails4.2.gemfile.lock
gemfiles/rails5.1.gemfile.lock
gemfiles/rails5.2.gemfile.lock
gemfiles/rails6.0.gemfile.lock
gemfiles/rails6.1.gemfile.lock

I cannot get the tests to run, and most people should use a newer Rails anyway.

Drop support for Rails 4.1 and below

---

.github/workflows/ci.yml
curly-templates.gemspec
gemfiles/rails4.2.gemfile.lock
gemfiles/rails5.1.gemfile.lock
gemfiles/rails5.2.gemfile.lock
gemfiles/rails6.0.gemfile
gemfiles/rails6.0.gemfile.lock
gemfiles/rails6.1.gemfile.lock
gemfiles/rails7.0.gemfile
gemfiles/rails7.0.gemfile.lock
spec/integration/context_blocks_spec.rb

Rails 7.0 is only compatible with Ruby 2.7+ so we don't test it with
Ruby 2.6
The form html that Rails 7.0 builds is slightly different compared to other versions of Rails so the html expectation of one test was updated.

Add support for Rails 7

---

.github/workflows/ci.yml
curly-templates.gemspec
gemfiles/rails4.2.gemfile.lock
gemfiles/rails5.1.gemfile.lock
gemfiles/rails5.2.gemfile.lock
gemfiles/rails6.0.gemfile.lock
gemfiles/rails6.1.gemfile.lock
gemfiles/rails7.0.gemfile.lock
lib/curly/presenter.rb
spec/spec_helper.rb

Add support for Ruby 3.0 & 3.1.
The `sorted_set` gem was removed from the standard library so we need to add it to the gemfiles explicitly.

Add support for Ruby 3.0 & 3.1

---

.github/workflows/ci.yml
.github/workflows/test_against_rails_main.yml
.gitignore
CHANGELOG.md
curly-templates.gemspec
gemfiles/rails6.1.gemfile.lock
gemfiles/rails7.0.gemfile.lock
gemfiles/rails7.1.gemfile.lock
gemfiles/rails_main.gemfile
lib/curly/version.rb

Release v3.4.0:
* Drop upper limit on Rails, test with Rails main.
* Drop support for Ruby < 3.1.
* Drop support for Rails < 6.1.

Drop upper limit on Rails, test Rails main, release v3.4.0

---

.github/workflows/publish.yml
CONTRIBUTING.md
Rakefile

Switches to [a Trusted Publishing workflow](https://guides.rubygems.org/trusted-publishing/).
This workflow will run whenever `version.rb` is changed in the `main` branch.
Setting `ENV["gem_push"]` is also not necessary anymore.
`bundler-cache` for `setup-ruby` is set to false to prevent [cache poisoning attacks](https://adnanthekhan.com/2024/05/06/the-monsters-in-your-build-cache-github-actions-cache-poisoning/).
Finally, we add a description of the new release process. Our README and CONTRIBUTING files don’t have a standard structure, so please check that we have updated a correct file and that the new section makes sense for this gem.

Switch to trusted publishing workflow and run it on version.rb changes
